from .department import KNOWN_DEPARTMENTS, extract_department_from_text, normalize_department
from .extract import extract_visitor_goal, extract_visitor_name
from .mode import normalize_contact_mode
from .service import detect_conversation_intent, message_may_require_contact_intent
